templ/urls.py
from django.urls import path,include
from rest_framework import routers
from . import views
from django.conf.urls import url
from django.urls import path
router = routers.DefaultRouter()


urlpatterns = [

    url('', include(router.urls)),
    path('<int:obj_id>/userdata/', views.userdata, name='userdata'),
    path('donation-reminder-sms/', views.donation_reminder_sms, name='donation_reminder_sms'),

# login logout reset password -->
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name= "logout"),
    path("password_reset", views.password_reset_request, name="password_reset"),

#donors creation -->
    path('donors_list/', views.DonorsListView.as_view(), name='donors_changelist'),
    path('add_donor/', views.DonorsCreateView.as_view(), name='donors_add'),
    path('<int:pk>/', views.DonorsUpdateView.as_view(), name='donors_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('dlt/<int:pk>', views.DonorsDelete.as_view(), name='donors_delete'),

# donation details -->
    path('donation_details/', views.DonationDetailsListView.as_view(), name='donation_details_changelist'),
    # path('add_donation/', views.DonationDetailsCreateView.as_view(), name='donation_add'),
    # path('a<int:pk>/', views.DonationDetailsUpdateView.as_view(), name='donation_change'),
    path('donation/add/', views.DonationTransactionCreate.as_view(), name='donation_addd'),
    path('donation/<int:pk>', views.DonationTransactionDetail.as_view(), name='donation-update'),
    path('delete/<int:pk>', views.Donation_DetailsDelete.as_view(), name='donation_delete'),


# bhaktamber catogry crate add update -->
    path('bhaktamber_category_list/', views.BhaktamberCategoryListView.as_view(), name='BhaktamberCategory_changelist'),
    path('add_bhaktamber/', views.BhaktamberCategoryCreateView.as_view(), name='bhaktamber_add'),
    path('b<int:pk>/', views.BhaktamberCategoryUpdateView.as_view(), name='bhaktamber_change'),


]

temple/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    #path('redirect', RedirectView.as_view(pattern_name='donors_changelist'), name='home'),
    path('', include('templ.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='templ/password/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="templ/password/password_reset_confirm.html"),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='templ/password/password_reset_complete.html'),name='password_reset_complete'),

    path('api-auth/', include('rest_framework.urls')),
    path('chaining/', include('smart_selects.urls')),
]

templ/models.py
from django.db import models
from django.utils.timezone import now
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
#from phone_field import PhoneField
from phonenumber_field.modelfields import PhoneNumberField
from smart_selects.db_fields import GroupedForeignKey, ChainedForeignKey, ChainedManyToManyField
from django.conf import settings
from twilio.rest import Client
from .utils import CITIES, state_choices


class State(models.Model):
    state_name = models.CharField( null=False, max_length=100, unique=True, )

    def __str__(self):
        return str(self.state_name)


class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    city_name = models.CharField(max_length=200, null=False, unique=True)

    def __str__(self):
        return str(self.city_name)

# class DonationStatus(models.Model):
#     id = models.AutoField(primary_key=True)
#     status = models.CharField(max_length=100, blank=False, unique=True, )
#
#     def __str__(self):
#         return str(self.status)


# class User(models.Model):
#     id = models.AutoField(primary_key=True)
#     name = models.CharField(max_length=100, default='')
#     mobile_number = PhoneNumberField(help_text='Mobile Format: +917028735596')
#
#     alternate_contact_number = PhoneNumberField(help_text='Alternate contact number')
#     address = models.CharField(max_length=100, default='')
#     adhar_number = models.CharField(max_length=50, default=None)
#     state = models.ForeignKey(State, on_delete=models.CASCADE)
#     city = ChainedForeignKey(
#         City,
#         chained_field="state",
#         chained_model_field="state",
#         show_all=False,
#         auto_choose=True,
#         default=None)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return self.name + str(self.mobile_number)


class BhaktamberCategories(models.Model):
    id = models.AutoField(primary_key=True)
    reason = models.CharField(max_length=100, blank=False,  unique=True, )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.reason




class UserDonation(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, default='')

    mobile_number = PhoneNumberField(help_text='Mobile Format: +917028735596', unique=True)
    address = models.CharField(max_length=100, default='')
    adhar_number = models.CharField(max_length=12, validators=[RegexValidator(r'^\d{12,12}$', message='Enter valid AADHAAR number', code='nomatch')], unique=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    # city = ChainedForeignKey(
    #     City,
    #     chained_field="state",
    #     chained_model_field="state",
    #     show_all=False,
    #     auto_choose=True,
    #     default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Donaties"

    def clean(self):
        pass

    def __str__(self):
        return str(self.mobile_number)


class Donation_Details(models.Model):  #Transaction_Details
    id = models.AutoField(primary_key=True)
    donor_details = models.ForeignKey(UserDonation, on_delete=models.CASCADE, )
    Bhaktamber_category = models.ForeignKey(BhaktamberCategories, on_delete=models.CASCADE)
    amount_regex = RegexValidator(regex=r'^[1-9][0-9]*$', message="Donation amount should be 1 or > 1 Rs'.")
    donation_amount = models.IntegerField(validators=[amount_regex], default=None, blank=False)
    total_received_amount = models.FloatField(default=0,blank=True, null=True, )
    current_received_amount = models.IntegerField(validators=[amount_regex], default=None, blank=False)
    total_painding_amount = models.FloatField(default=0,blank=True, null=True, )
    donation_date = models.DateField(default=None)
    donation_status = models.CharField(max_length=100, )
    donation_deposit_date = models.DateField(default=None, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)  # auto_now_add=True
    updated_at = models.DateTimeField(auto_now=True)  # auto_now=True

    class Meta:
        verbose_name_plural = "Donation_Details"


    def __str__(self):
        return str(self.donation_amount)

    def applicant_donor_details(self):
        return self.donor_details.mobile_number
    applicant_donor_details.short_description = 'Applicant Mobile Number'

    def applicant_name(self):
        return self.donor_details.name
    applicant_name.short_description = 'Applicant Name'

    def applicant_state(self):
        return self.donor_details.state
    applicant_state.short_description = 'State'

    def Donation_Category(self):
        return self.Bhaktamber_category.reason
    Donation_Category.short_description = 'Bhaktamber Category'

    def applicant_address(self):
        return self.donor_details.address
    applicant_address.short_description='Address'

    def save(self, *args, **kwargs):
        self.total_received_amount = int(self.total_received_amount + self.current_received_amount)
        self.total_painding_amount = int(self.donation_amount - self.total_received_amount)
        if self.total_received_amount==self.donation_amount:
            self.donation_status='Paid'
        elif self.total_received_amount < self.donation_amount:
            self.donation_status = 'Partialy Paid'
        elif self.total_received_amount==0:
            self.donation_status = 'Unaid'
        super().save(*args, **kwargs)

        # mobile_number = self.donor_details
        # first_name = self.applicant_name
        # donation_amount = self.current_received_amount
        # donation_status = self.donation_status
        # message_to_broadcast = (f"Thanks {first_name}, For Paying donation Of Rs. {donation_amount}.")
        # client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
        # # mobile_number="+91"+mobile_number
        # if donation_status == 'PAID' or 'PARTIALY PAID':
        #     client.messages.create(to=mobile_number,
        #                            from_=settings.TWILIO_NUMBER,
        #                            body=message_to_broadcast)
        #     print('Message sent successfully.')
        # else:
        #     pass



class Transaction_Details(models.Model):
    donation_details = models.ForeignKey(Donation_Details, on_delete=models.CASCADE)
    # total_amount = models.ForeignKey(Donation_Details, on_delete=models.CASCADE)
    amount_regex = RegexValidator(regex=r'^[1-9][0-9]*$', message="Donation amount should be 1 or > 1 Rs'.")
    current_received_amount = models.IntegerField(validators=[amount_regex], default=None, blank=False)
    # painding_amount = models.IntegerField(validators=[amount_regex], default=None, blank=False)
    donation_deposit_date = models.DateField(default=None)




    def __str__(self):
        return str(self.received_amount)

templ/forms.py
from django.forms import ModelForm,inlineformset_factory
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import  State, City, BhaktamberCategories,UserDonation,Donation_Details, Transaction_Details
# class UserForm(ModelForm):
#     class Meta:
#         model=User
#         fields=['name','mobile_number','adhar_number','alternate_contact_number','address']


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user




class UserDonationForm(ModelForm):
    class Meta:
        model=UserDonation
        fields=['name','mobile_number','adhar_number','address', 'state','city']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()


        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('city_name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.state.city_set.order_by('city_name')

class Donation_DetailsForm(ModelForm):
    class Meta:
        model=Donation_Details
        fields = ('__all__')
        widgets ={
            'total_received_amount': forms.HiddenInput(),
            'total_painding_amount': forms.HiddenInput(),
        }
        exclude = ()

class Transaction_DetailsForm(ModelForm):
    class Meta:
        model=Transaction_Details
        fields = ('__all__')
        exclude = ()

Transaction_DetailsFormSet = inlineformset_factory(Donation_Details, Transaction_Details, form=Transaction_DetailsForm, extra=0)


class BhaktamberCategoryForm(ModelForm):
    class Meta:
        model = BhaktamberCategories
        fields = ['reason']

templ/templates/templ/BhaktamberCategory.html
{% extends 'base.html' %}

{% block content %}
<body>
    <form method="POST" action="" style="background-color:cyan"  novalidate>
        {% csrf_token %}
        <table style="text-align: left; color:#0D39EA; background-color:#1AE83F;  ">
        {{ form.as_table }}
        </table>
        <input type="submit" value="Save">
        <a href="{% url 'BhaktamberCategory_changelist' %}">Back to bhaktamber list</a>
    </form>

</body>
</html>

{% endblock %}

templ/templates/templ/DonationDetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{{ form.media }} <!-- for datepicker  -->
<body >
    <div class="col-md-4">
    <a href="{% url 'donors_add' %}" ><button type="button" style="color: #3333FF; background-color:#FFF933;">Add new donar</button></a>
    <form method="POST" action=""   novalidate >
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <br><br>
        <table class="table" style="text-align: left; ">


                {{ transaction_details.management_form }}

                {% for form in transaction_details.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="{% cycle row1 row2 %} formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}


        </table>


        <input type="submit" value="Save"  >  <!--name="donation" id="donation" -->
        <a href="{% url 'donation_details_changelist' %}"> <button type="button" style=" color: black">Back to donations list</button></a>

    </form>
    </div>
<!-- installment tracking start -->
    <script src="{% static 'formset/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'add current received amount ',
            deleteText: 'remove',
            prefix: 'transaction_details_set'
        });
    </script>
<!-- installment tracking finish  -->

<!-- Autocomplete field -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        // In your Javascript (external .js resource or <script> tag)
        $(document).ready(function() {
        $('#id_donor_details').select2();
        });
    </script>
<!-- Autocomplete field -->

<!--http://jsfiddle.net/0vt8z6jc/17/    AUTOFILL BOX    jquery link for demo autofill box code  -->
    <script>
        $('#id_current_received_amount').keyup(function() {
        var current_received_amount = $('#id_current_received_amount').val();
        var crAmount = current_received_amount;
        $('#id_transaction_details_set-0-current_received_amount').val(crAmount);
        });

        $('#id_donation_deposit_date').keyup(function() {
        var donation_deposit_date = $('#id_donation_deposit_date').val();
        var Date = donation_deposit_date;
        $('#id_transaction_details_set-0-donation_deposit_date').val(Date);
        });
    </script>

</body>
</html>

{% endblock %}

templ/templates/templ/Donation_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h2></h2>
    <hr>
    <div>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
<!--            <input type="submit" value="Confirm" />-->
            <input class="btn btn-success" type="submit" value="Confirm" />
<!--            <input type="submit" name="cancel" value="Cancel" />-->
            <a href="{{ view.get_success_url }}" class="btn btn-success">Cancel</a>
        </form>
    </div>
{% endblock %}

templ/templates/templ/bhaktamber_category_list.html
{% extends 'base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}

  <p>
    <a href="{% url 'bhaktamber_add' %}">Add bhakmber category</a>
  </p>

  <table  id="dtHorizontalVerticalExample" class="table table-striped table-bordered table-sm " cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Bhaktamber category</th>

      </tr>
    </thead>
    <tbody>
      {% for BhaktamberCategories in BhaktamberCategoriesList %}
        <tr>
          <td><a href="{% url 'bhaktamber_change' BhaktamberCategories.pk %}">{{ BhaktamberCategories.reason }}</a></td>

        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No category in the database. <a href="{% url 'bhaktamber_add' %}">Add the first bhaktamber category</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

templ/templates/templ/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.city_name }}</option>
{% endfor %}

templ/templates/templ/donatees.html
{% extends 'base.html' %}

{% block content %}
<body>
    <div >
    <form method="POST" action="" style="background-color:#AAAAAC " id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
        {% csrf_token %}
        <table style="text-align: left; color:#0D39EA; background-color:#12FB07 ;  ">
        {{ form.as_table }}
        </table>
        <input type="submit" value="Save">
        <a href="{% url 'donors_changelist' %}"><button type="button" style="color: blue">Back to donors list</button></a>
    </form>
    </div>
<!--  STATE CITY DROPDOWN JQUERY CODE -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_state").change(function () {
      var url = $("#personForm").attr("data-cities-url");
      var stateId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'state': stateId
        },
        success: function (data) {
          $("#id_city").html(data);
        }
      });

    });
  </script>

</body>
</html>

{% endblock %}

templ/templates/templ/donatees_list.html
{% extends 'base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}

  <p>
    <a href="{% url 'donors_add' %}"><button type="button" style="color: red">Add new donor</button></a>
  </p>
  <div class="table-responsive">
  <table id="HorizontalVerticalExample" class="table table-striped table-bordered table-sm " cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Mobile Number</th>
        <th>Address</th>
        <th>Adhar Number</th>
        <th class="select-filter">State</th>
        <th class="select-filter">City</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for UserDonation in donorslist %}
        <tr>
          <td><a href="{% url 'donors_change' UserDonation.pk %}">{{ UserDonation.name }}</a></td>
          <td>{{UserDonation.mobile_number }}</td>
          <td>{{UserDonation.address }}</td>
          <td>{{UserDonation.adhar_number }}</td>
          <td>{{ UserDonation.state.state_name }}</td>
          <td>{{ UserDonation.city.city_name }}</td>
          <td><a href="{% url 'donors_delete' UserDonation.pk %}">Delete</a></td>

        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No donors in the database. <a href="{% url 'donors_add' %}">Add the first donor</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
<!--    <script>-->
<!--        $(document).ready(function(){-->
<!--        $('#dtHorizontalVerticalExample').dataTable(-->
<!--        {"scrollX": true,-->
<!--          "scrollY": 200,}-->
<!--        );-->

<!--        });-->
<!--    </script>-->
    <tfoot>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>

        </tr>
    </tfoot>
  </table>
  </div>
{% endblock %}

templ/templates/templ/donation_details_list.html
{% extends 'base.html' %}



{% block content %}

  <p>
    <a href="{% url 'donation_addd' %}"><button type="button" style="color: red">Add donation</button></a>
  </p>
  <div class="table-responsive" >
<!--    <div id="example" class="display" style="width:100%">-->


  <table id="HorizontalVerticalExample" class="table table-striped table-bordered table-sm "  cellspacing="0" width="100%"  >

    <thead>
      <tr>
        <th>Name</th>
        <th>Aadhar</th>
        <th>Phone</th>
        <th class="select-filter">State</th>
        <th class="select-filter">City</th>
        <th class="select-filter">Category</th>
        <th>Date</th>
        <th>Promised Donation</th>
        <th>Current Received</th>
        <th>Total Received</th>
        <th>Pending</th>
        <th>Status</th>
        <th>Print</th>
        <th>Action</th>
      </tr>

    </thead>
    <tbody>
      {% for Donation_Details in DonationDetailsList %}

        <tr>
          <td><a href="{% url 'donation-update' Donation_Details.pk %}">{{ Donation_Details.donor_details.name }}</a></td>
          <td>{{ Donation_Details.donor_details.adhar_number }}</td>
          <td>{{Donation_Details.donor_details.mobile_number }}</td>
          <td>{{ Donation_Details.donor_details.state }}</td>
          <td>{{ Donation_Details.donor_details.city }}</td>
          <td>{{Donation_Details.Bhaktamber_category }}</td>
          <td>{{ Donation_Details.donation_deposit_date }}</td>
          <td>{{Donation_Details.donation_amount }}</td>
          <td>{{ Donation_Details.current_received_amount }}</td>
          <td>{{Donation_Details.total_received_amount }}</td>
          <td>{{ Donation_Details.total_painding_amount }}</td>
          <td>{{ Donation_Details.donation_status }}</td>
          <td><a href="/{{Donation_Details.id}}/userdata/"  target="blank">Print</a> </td>
          <td><a href="{% url 'donation_delete' Donation_Details.pk %}">Delete</a></td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No donation details in the database. <a href="{% url 'donation_addd' %}">Add the first donation detail</a>.</td>
        </tr>
      {% endfor %}
    </tbody>


    <tfoot >
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
    </tfoot>

  </table>
  </div>
  </div>

{% endblock %}

templ/templates/templ/login.html
{% extends "header.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Login-->
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
    <a href="/password_reset">Forgot password?</a>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock %}

templ/templates/templ/register.html
{% extends "header.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

templ/templates/templ/transaction_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--                        Datepicker links                        -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<body >
    <div class="col-md-4">

        {{ object.donor_details.name }} ({{ object.donor_details.mobile_number }}) <br>
        Category: {{ object.Bhaktamber_category }} <br>
        Promised Donation: {{ object.donation_amount }} <br>
        Status: {{ object.donation_status }} <br>
        <br>

        <h4 style=" margin-top:0px; margin-bottom:0px;">Transaction Details:</h4>
        <h4 style=" margin-top:0px; margin-bottom:0px;">__________________________________</h4>
        <table class="table" style="text-align: left; ">
            <thead>
                <tr>
                    <th> Received Amount </th>
                    <th> Received Date </th>
                </tr>
            </thead>
            {% for transaction in object.transaction_details_set.all%}
                <tbody>
                    <tr>
                        <td>{{ transaction.current_received_amount }}</td>
                        <td>{{ transaction.donation_deposit_date}}</td>
                     </tr>
                </tbody>
            {% endfor %}
        </table><br><br>

    <form  method="POST" action="" >
        {% csrf_token %}
        <input placeholder="Amount" name="amount">
        <input placeholder="Date" type="text" id="datepicker" name="date">
        <button value="Add Donation"> Add donation </button>
    </form>

<!--        Datepicker Jquery               link for code:- https://www.codexworld.com/add-datepicker-to-input-field-jquery-ui/  -->
    <script>
        $(function(){
        $("#datepicker").datepicker({
        changeMonth: true,
        changeYear: true
        });
        });
    </script>

    </div>
</body>
</html>

{% endblock %}